[GLOBAL]
pants_version = "2.16.0"

backend_packages = [
  "pants.backend.python",
  "pants.backend.experimental.python",

  "pants.backend.experimental.go",
  "pants.backend.shell",
]

[source]
root_patterns = [
  '/src/go/generator/',
]

[anonymous-telemetry]
enabled = false
